### ISSUE TITLE
radar uitlezen op de borden

### ISSUE THREAD

**Issue by Jettypanini** [randomRexx/ADAS_AI_cart#17]

**Comment by cteqeu** [comment]
Werkt de radar?
 Zorg dat je bewijsstukken toevoegd aan het ticket.

Mvg
Vincent
________________________________
Van: Nightwolve <notifications@github.com>
Verzonden: dinsdag 24 maart 2020 12:41
Aan: randomRexx/ADAS_AI_cart <ADAS_AI_cart@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [randomRexx/ADAS_AI_cart] radar uitlezen op de borden (#17)


Closed #17<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FrandomRexx%2FADAS_AI_cart%2Fissues%2F17&data=02%7C01%7Cvincent.claes%40pxl.be%7Ca633f11f18eb4ef47e9808d7cfe85111%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637206469018975780&sdata=R7taGGJEpizIN0d8zZFGDwlIlbI0y3Sfkc1BtAqNMEk%3D&reserved=0>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FrandomRexx%2FADAS_AI_cart%2Fissues%2F17%23event-3159271616&data=02%7C01%7Cvincent.claes%40pxl.be%7Ca633f11f18eb4ef47e9808d7cfe85111%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637206469018985782&sdata=2CTYiWIPJ3GpC4hbHtfUmyM3Mw5adz0EiuXi6MCfWkM%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABJVUVKCSE2HVUQFEAOKMDLRJCL7FANCNFSM4LOKJGSQ&data=02%7C01%7Cvincent.claes%40pxl.be%7Ca633f11f18eb4ef47e9808d7cfe85111%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637206469018985782&sdata=fPvb3%2FQAOd0q17ljFchwO%2B0DHa5T6HNCG%2FgedfFKBqM%3D&reserved=0>.





[http://www.pxl.be/Assets/afbeeldingen_algemeen/MailFootersPXL/Footer%20infodag%2025_04_2020_210.jpg]

**Comment by cteqeu** [comment]
Waarom stuck?

**Comment by Jettypanini** [comment]
Mijn excuses dat ik dit nu pas reageer. Ik heb de radar aan de praat gekregen, met ROS drivers. Het filmpje staat in de Zedboard branch.
Nu ben ik er, via Python, de X- en Y-waarden aan het proberen uithalen, alsook met de Pytorch kennis aan het maken. 
Zo kan ik voor de camera-beelden een overlay maken, met de radar waarden.

Met vriendelijke groeten

Jethro Pans
