### ISSUE TITLE
Vitis AI DNNDK voor ultra96 installeren.

### ISSUE THREAD

**Issue by Nightwolve** [randomRexx/ADAS_AI_cart#53]
de build die ik vorig jaar gebruikt heb is niet meer beschikbaar. is sindsdien een forum topic geworden zonder oplossing tot heden. zijn nog op zoek 
https://forums.xilinx.com/t5/AI-and-Vitis-AI/Where-can-I-find-DNNDK-3-0-Package/td-p/1164484 

https://www.element14.com/community/message/297944/l/ultra96-wi-fi-problem#297944

**Comment by cteqeu** [comment]
https://www.hackster.io/AlbertaBeef/vitis-ai-1-1-flow-for-avnet-vitis-platforms-part-1-007b0e
https://www.hackster.io/AlbertaBeef/vitis-ai-1-1-flow-for-avnet-vitis-platforms-part-2-f18be4

**Comment by i5cP7i** [comment]
https://www.hackster.io/AlbertaBeef/vitis-ai-1-1-flow-for-avnet-vitis-platforms-part-1-007b0e

Xilinx tools installation: successfully completed.

@Building Hardware project:

make command fails due to a path error.

![VirtualBoxVM_wUQNFhsLYj](https://user-images.githubusercontent.com/48355782/97643478-0a6fd200-1a48-11eb-9e9f-2c55a21c1e9b.png)

After hardcoding the Vivado install path of Makefile the command still fails.

![VirtualBoxVM_OgwStKydKn](https://user-images.githubusercontent.com/48355782/97643485-0f348600-1a48-11eb-98ce-44d7bb5ea4d0.png)

The above screenshot shows that the path may be illegal. Starting over building the hardware project in a new directory resolves the path issue. A dpu.xo and softmax.xo containing the ip_repo etc. and kernel packages are now created. However, the build still fails:

![VirtualBoxVM_gHDEoeB7kV](https://user-images.githubusercontent.com/48355782/97643487-1196e000-1a48-11eb-8681-d778754fd6cd.png)

Make fails to invoke Vitis' v++ compiler. Installing the packages listed on pages 10-11 from the Xilinx software manual and/or reinstalling Ubuntu (different version) and reinstalling the Vitis platform may be potential solutions to this problem.

https://www.xilinx.com/support/documentation/sw_manuals/xilinx2019_2/ug1144-petalinux-tools-reference-guide.pdf

**Comment by cteqeu** [comment]
Did you install vitis on this linux development machine ?

Van: i5cP7i <notifications@github.com>
Verzonden: vrijdag 30 oktober 2020 0:54
Aan: randomRexx/ADAS_AI_cart <ADAS_AI_cart@noreply.github.com>
CC: Vincent Claes <Vincent.Claes@PXL.BE>; Comment <comment@noreply.github.com>
Onderwerp: Re: [randomRexx/ADAS_AI_cart] Vitis AI DNNDK voor ultra96 installeren. (#53)


https://www.hackster.io/AlbertaBeef/vitis-ai-1-1-flow-for-avnet-vitis-platforms-part-1-007b0e<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.hackster.io%2FAlbertaBeef%2Fvitis-ai-1-1-flow-for-avnet-vitis-platforms-part-1-007b0e&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275256303%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FMHsk%2FEMwvlF%2B4s%2FLh8quc0k6G0pSQZEWKPB2BaZCu8%3D&reserved=0>

Xilinx tools installation: successfully completed.

@building<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbuilding&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275256303%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R6O50WswwkXQTq97PPK7ZdcEO4xUOqfWldAGytVdcYo%3D&reserved=0> Hardware project:

make command fails

[VirtualBoxVM_wUQNFhsLYj]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48355782%2F97643478-0a6fd200-1a48-11eb-9e9f-2c55a21c1e9b.png&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275266296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BqUFui16vRGm%2FGeITKXiMKjZ12AE9o71kg17t%2Bz8oO0%3D&reserved=0>

After hardcoding Vivado install path of Makefile:

[VirtualBoxVM_OgwStKydKn]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48355782%2F97643485-0f348600-1a48-11eb-98ce-44d7bb5ea4d0.png&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275266296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7n%2BFe2V4%2FyLXCxlP2xYN9YH9eZKbPhnlrC9Qr7XWhns%3D&reserved=0>

Above screenshot shows that the path may be illegal. Starting over building the hardware project in a new directory resolves the path issue. A dpu.xo and softmax.xo containing the ip_repo etc. and kernel packages are now created. However, the build still fails:

[VirtualBoxVM_gHDEoeB7kV]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48355782%2F97643487-1196e000-1a48-11eb-8681-d778754fd6cd.png&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275276294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OjPH3tztW5FJK1Eo1094EId9TLU5qDe1zSZhRUS8W2Q%3D&reserved=0>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FrandomRexx%2FADAS_AI_cart%2Fissues%2F53%23issuecomment-719088567&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275276294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ECjTpi7q%2FrXLc2V5YiD853O9g1aDmi9UHyLtJajQHZo%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABJVUVJK3QRZKWTIJVRSHDLSNH6ARANCNFSM4S4MHBLQ&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275286286%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9E3Ulfi%2Bs6g16UpRvfMk4zj3%2BtG2C4iJ81984nRnTG4%3D&reserved=0>.





[http://www.pxl.be/Assets/afbeeldingen_algemeen/MailFootersPXL/Footer_infodag_18_11.jpg]

**Comment by i5cP7i** [comment]
> Did you install vitis on this linux development machine ? Van: i5cP7i <notifications@github.com> Verzonden: vrijdag 30 oktober 2020 0:54 Aan: randomRexx/ADAS_AI_cart <ADAS_AI_cart@noreply.github.com> CC: Vincent Claes <Vincent.Claes@PXL.BE>; Comment <comment@noreply.github.com> Onderwerp: Re: [randomRexx/ADAS_AI_cart] Vitis AI DNNDK voor ultra96 installeren. (#53) https://www.hackster.io/AlbertaBeef/vitis-ai-1-1-flow-for-avnet-vitis-platforms-part-1-007b0e<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.hackster.io%2FAlbertaBeef%2Fvitis-ai-1-1-flow-for-avnet-vitis-platforms-part-1-007b0e&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275256303%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FMHsk%2FEMwvlF%2B4s%2FLh8quc0k6G0pSQZEWKPB2BaZCu8%3D&reserved=0> Xilinx tools installation: successfully completed. @building<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbuilding&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275256303%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R6O50WswwkXQTq97PPK7ZdcEO4xUOqfWldAGytVdcYo%3D&reserved=0> Hardware project: make command fails [VirtualBoxVM_wUQNFhsLYj]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48355782%2F97643478-0a6fd200-1a48-11eb-9e9f-2c55a21c1e9b.png&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275266296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BqUFui16vRGm%2FGeITKXiMKjZ12AE9o71kg17t%2Bz8oO0%3D&reserved=0> After hardcoding Vivado install path of Makefile: [VirtualBoxVM_OgwStKydKn]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48355782%2F97643485-0f348600-1a48-11eb-98ce-44d7bb5ea4d0.png&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275266296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7n%2BFe2V4%2FyLXCxlP2xYN9YH9eZKbPhnlrC9Qr7XWhns%3D&reserved=0> Above screenshot shows that the path may be illegal. Starting over building the hardware project in a new directory resolves the path issue. A dpu.xo and softmax.xo containing the ip_repo etc. and kernel packages are now created. However, the build still fails: [VirtualBoxVM_gHDEoeB7kV]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48355782%2F97643487-1196e000-1a48-11eb-8681-d778754fd6cd.png&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275276294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OjPH3tztW5FJK1Eo1094EId9TLU5qDe1zSZhRUS8W2Q%3D&reserved=0> — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FrandomRexx%2FADAS_AI_cart%2Fissues%2F53%23issuecomment-719088567&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275276294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ECjTpi7q%2FrXLc2V5YiD853O9g1aDmi9UHyLtJajQHZo%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABJVUVJK3QRZKWTIJVRSHDLSNH6ARANCNFSM4S4MHBLQ&data=04%7C01%7Cvincent.claes%40pxl.be%7Cabf8c7860c8b4017784b08d87c65e001%7C0bff66c545db46ed8b8187959e069b90%7C0%7C0%7C637396124275286286%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9E3Ulfi%2Bs6g16UpRvfMk4zj3%2BtG2C4iJ81984nRnTG4%3D&reserved=0>. [http://www.pxl.be/Assets/afbeeldingen_algemeen/MailFootersPXL/Footer_infodag_18_11.jpg]

Discussed on MS Teams

**Comment by Nightwolve** [comment]
Changed SD-Card and it magically worked! apparently Samsung SD-Card are not compatible with the Ultra96

**Comment by Nightwolve** [comment]
Made post on forum, hardstuck bug atm JTAG is not working and Wi-Fi is not connecting.
https://www.element14.com/community/message/297944/l/ultra96-wi-fi-problem#297944
